create schema if not exists reg;

create table if not exists reg.waitlist_signups (
  id integer generated by default as identity primary key,
  email text not null unique,
  name text,
  platform text,
  emirate text,
  message text,
  consent boolean not null default false,
  created_at timestamptz not null default now()
);

alter table reg.waitlist_signups enable row level security;

grant usage on schema reg to service_role;
grant select, insert, update, delete on all tables in schema reg to service_role;
grant usage, select on all sequences in schema reg to service_role;
